ALTER TABLE personal_info ADD COLUMN IF NOT EXISTS job_title VARCHAR(150);
ALTER TABLE personal_info ADD COLUMN IF NOT EXISTS github_url VARCHAR(500);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS strengths TEXT;
